'use client'

import { useState } from 'react'
import { useCompanyContext } from '@/hooks/use-company-context'
import { useCurrentForecast } from '@/hooks/use-current-forecast'
import { Download, Loader2, Printer } from 'lucide-react'
import { formatCompact } from '@/hooks/use-format-currency'
import { cn } from '@/lib/utils'
import { HeaderBadge, PageHeader, SurfaceCard } from '@/components/shared/page-header'

// Need to dynamically import html2canvas and jspdf to avoid SSR issues
// In-browser dynamically imported to avoid window issues in SSR
const exportPdf = async (elementId: string, filename: string) => {
  const html2canvas = (await import('html2canvas')).default
  const jsPDF = (await import('jspdf')).jsPDF
  const element = document.getElementById(elementId)
  if (!element) return

  // Temporarily prep the element for printing
  const originalStyle = element.style.cssText
  element.style.background = '#ffffff'
  element.style.color = '#000000'
  element.style.padding = '20px'
  element.style.width = '210mm'
  element.style.minHeight = '297mm'

  try {
    const canvas = await html2canvas(element, { scale: 2, useCORS: true })
    const imgData = canvas.toDataURL('image/png')
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    })

    const pdfWidth = pdf.internal.pageSize.getWidth()
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width

    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight)
    pdf.save(`${filename}.pdf`)
  } finally {
    // Restore
    element.style.cssText = originalStyle
  }
}

export default function ReportsPage() {
  const { company, isCA, isLoading } = useCompanyContext()
  const { engineResult } = useCurrentForecast()
  const [isExporting, setIsExporting] = useState(false)
  const [reportTitle, setReportTitle] = useState('Executive Financial Summary')
  const [firmBranding, setFirmBranding] = useState(isCA ? 'Generated by CA Partner' : '')

  if (isLoading) {
    return (
      <div className="flex h-[60vh] items-center justify-center">
        <div className="flex flex-col items-center gap-3">
          <Loader2 className="h-8 w-8 animate-spin text-emerald-400" />
          <p className="text-sm text-slate-400">Loading report data...</p>
        </div>
      </div>
    )
  }

  const handleExport = async () => {
    if (!company) return
    setIsExporting(true)
    try {
      await exportPdf('report-content', `${company.name.replace(/\s+/g, '_')}_Forecast_Report`)
    } catch (err) {
      console.error('Failed to export PDF:', err)
    } finally {
      setIsExporting(false)
    }
  }

  const months = engineResult?.forecastMonths || []
  const netIncomeRow = engineResult?.integrationResults.map(m => m.pl.netIncome) || []
  const cashRow = engineResult?.integrationResults.map(m => m.cf.netCashFlow) || []

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Reports"
        title="Report Builder"
        description="Package the current forecast into a polished PDF export with clean executive summaries and client-ready branding."
        badges={
          <>
            <HeaderBadge label={company?.name ?? 'No company'} />
            <HeaderBadge label={months.length > 0 ? `${months.length} months in report` : 'Awaiting forecast'} tone={months.length > 0 ? 'success' : 'warning'} />
          </>
        }
        actions={
          <button
            onClick={handleExport}
            disabled={isExporting}
            className="inline-flex items-center gap-2 rounded-full bg-emerald-500 px-4 py-2 text-sm font-semibold text-slate-950 transition hover:bg-emerald-400 disabled:opacity-50"
          >
            {isExporting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
            {isExporting ? 'Generating PDF...' : 'Download PDF'}
          </button>
        }
      />

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-4">
        {/* Settings Sidebar */}
        <div className="space-y-4 lg:col-span-1">
          <SurfaceCard className="space-y-5">
            <div>
              <p className="text-sm font-medium text-white">Report Options</p>
              <p className="text-xs text-slate-400">Customize the header and branding for the exported PDF.</p>
            </div>
            <div className="space-y-4">
              <div>
                <label className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-400">Report Title</label>
                <input
                  type="text"
                  value={reportTitle}
                  onChange={(e) => setReportTitle(e.target.value)}
                  className="surface-input mt-2"
                />
              </div>
              {isCA && (
                <div>
                  <label className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-400">Custom Branding (CA Firm)</label>
                  <input
                    type="text"
                    value={firmBranding}
                    onChange={(e) => setFirmBranding(e.target.value)}
                    placeholder="e.g. Acme Associates"
                    className="surface-input mt-2"
                  />
                </div>
              )}
            </div>
          </SurfaceCard>
        </div>

        {/* Print Preview Canvas */}
        <div className="lg:col-span-3">
          <div className="overflow-hidden rounded-[24px] border border-white/8 bg-white shadow-[0_20px_60px_rgba(2,6,23,0.2)]">
            <div className="flex items-center border-b border-slate-200 bg-slate-50 p-3">
              <Printer className="mr-2 h-4 w-4 text-slate-500" />
              <span className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-500">
                A4 Document Preview
              </span>
            </div>
            
            {/* The actual printable area */}
            <div
              id="report-content"
              className="p-10 text-slate-900"
              style={{ width: '100%', minHeight: '600px', backgroundColor: '#fff', color: '#000' }}
            >
              {/* Report Header */}
              <div className="mb-8 flex items-end justify-between border-b pb-6 border-slate-200">
                <div>
                  <h1 className="text-3xl font-bold tracking-tight text-slate-900">
                    {company?.name || 'Company Name'}
                  </h1>
                  <h2 className="mt-2 text-xl font-medium text-slate-600">{reportTitle}</h2>
                </div>
                <div className="text-right">
                  <p className="text-sm font-semibold text-slate-500">
                    Generated: {new Date().toLocaleDateString('en-IN')}
                  </p>
                  {firmBranding && (
                    <p className="mt-1 text-sm font-bold text-emerald-600">
                      {firmBranding}
                    </p>
                  )}
                </div>
              </div>

              {/* KPI Summary Strip */}
              <div className="mb-10 flex gap-6">
                <div className="flex-1 rounded-xl bg-slate-50 p-4 border border-slate-100">
                  <p className="text-xs font-medium uppercase tracking-wider text-slate-500">Active Quarters</p>
                  <p className="mt-1 text-2xl font-bold text-slate-900">{Math.ceil(months.length / 3)}</p>
                </div>
                <div className="flex-1 rounded-xl bg-emerald-50 p-4 border border-emerald-100">
                  <p className="text-xs font-medium uppercase tracking-wider text-emerald-600">Avg Monthly Net</p>
                  <p className="mt-1 text-2xl font-bold text-emerald-700">
                    {formatCompact(netIncomeRow.reduce((a, b) => a + b, 0) / (netIncomeRow.length || 1))}
                  </p>
                </div>
                <div className="flex-1 rounded-xl bg-sky-50 p-4 border border-sky-100">
                  <p className="text-xs font-medium uppercase tracking-wider text-sky-600">Total Cash Movement</p>
                  <p className="mt-1 text-2xl font-bold text-sky-700">
                    {formatCompact(cashRow.reduce((a, b) => a + b, 0))}
                  </p>
                </div>
              </div>

              {/* Forecast Highlights Table */}
              <div className="mb-8">
                <h3 className="mb-4 text-lg font-bold text-slate-900 border-b border-slate-200 pb-2">
                  Forecast Summary (By Month)
                </h3>
                <div className="overflow-x-auto">
                  <table className="w-full text-left text-sm">
                    <thead>
                      <tr className="border-b border-slate-200 text-slate-500">
                        <th className="py-2 pr-4 font-semibold uppercase tracking-wider">Month</th>
                        <th className="py-2 px-4 text-right font-semibold uppercase tracking-wider">Net Income</th>
                        <th className="py-2 pl-4 text-right font-semibold uppercase tracking-wider">Net Cash Flow</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {months.slice(0, 12).map((month, idx) => (
                        <tr key={month}>
                          <td className="py-2 pr-4 font-medium text-slate-900">{month}</td>
                          <td className="py-2 px-4 text-right font-mono text-slate-600">
                            {formatCompact(netIncomeRow[idx] || 0)}
                          </td>
                          <td className={cn("py-2 pl-4 text-right font-mono font-medium", (cashRow[idx] || 0) < 0 ? "text-red-600" : "text-emerald-600")}>
                            {formatCompact(cashRow[idx] || 0)}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                {months.length > 12 && (
                  <p className="mt-3 text-xs text-slate-400 italic">
                    * Showing first 12 months only for summary view.
                  </p>
                )}
              </div>

              {/* Footer */}
              <div className="mt-16 text-center text-xs text-slate-400">
                <p>Generated securely by CashFlowIQ - Financial Forecasting & Planning</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
